#!/bin/sh -xe

export COMPONENT_NAME=${COMPONENT_NAME:-nginxing}
export DOMAIN_NAME=${DOMAIN_NAME:-test.dev.superhub.io}
export NAMESPACE=${NAMESPACE:-ingress}

HELM_REPO=https://kubernetes.github.io/ingress-nginx
HELM_CHART=ingress-nginx/ingress-nginx
CHART_VERSION=3.10.1

export kubectl="kubectl --context=$DOMAIN_NAME --namespace=$NAMESPACE"
export helm="helm3 --kube-context=$DOMAIN_NAME --namespace $NAMESPACE"

# TODO no HELM_HOME in Helm 3
# https://helm.sh/docs/faq/#xdg-base-directory-support
# Helm stores cache, configuration, and data based on the following configuration order:
# - If a HELM_*_HOME environment variable is set, it will be used
# - Otherwise, on systems supporting the XDG base directory specification, the XDG variables will be used
# - When no other location is set a default location will be used based on the operating system
#export HELM_HOME=$(pwd)/.helm

rm -rf charts
mkdir -p charts

if $helm list --failed --pending -q | grep -E "^$COMPONENT_NAME\$"; then
	  $helm uninstall $COMPONENT_NAME
fi

if test -x pre-deploy; then
    ./pre-deploy
fi

$helm repo add stable https://charts.helm.sh/stable
$helm repo add ingress-nginx $HELM_REPO
$helm repo update
$helm fetch $HELM_CHART --destination charts --untar --version $CHART_VERSION
$helm upgrade $COMPONENT_NAME charts/$(basename $HELM_CHART) \
    --install --wait --values values.yaml --version $CHART_VERSION

if test -x post-deploy; then
    ./post-deploy
fi
