#!/bin/sh

if test -z "$COMPONENT_NAME" -o -z "$DOMAIN_NAME" -o -z "$NAMESPACE"; then
    echo "COMPONENT_NAME, DOMAIN_NAME, NAMESPACE must be set"
    exit 1
fi

export kubectl="kubectl --context=$DOMAIN_NAME --namespace=$NAMESPACE"
export helm="helm3 --kube-context=$DOMAIN_NAME --namespace $NAMESPACE"

set -xe

if test -x pre-undeploy; then
    ./pre-undeploy
fi

if $helm list -q | grep -E "^$COMPONENT_NAME\$"; then
	  $helm uninstall $COMPONENT_NAME
fi

if test -x post-undeploy; then
    ./post-undeploy
fi
