apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
type: Opaque
data:
  password: c3VwZXJzZWNyZXQ=
  db-url: cG9zdGdyZXM6Ly9wb3N0Z3JlczpzdXBlcnNlY3JldEBwb3N0Z3Jlc3FsOjU0MzIvcG9zdGdyZXM/c3NsbW9kZT1kaXNhYmxl

