---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: traefik-acme
  labels:
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "default"
