{
 "title": "Argo",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Workflow",
    "query": "label_values(argo_workflow_info,workflow)"
   },
   {
    "name": "Node",
    "query": "query_result(argo_workflow_node_info{workflow=\"$Workflow\"})"
   },
   {
    "name": "Pod",
    "query": "query_result(argo_workflow_node_info{workflow=\"$Workflow\",type=\"Pod\"})"
   },
   {
    "name": "Phase",
    "query": "query_result(argo_workflow_status_phase{workflow=\"$Workflow\"} > 0)"
   }
  ]
 },
 "panels": [
  { "title": "Workflow details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Workflow duration",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "dthms",
   "valueName": "current",
   "targets": [
    {
     "expr": "argo_workflow_status_completion_time{workflow=\"$Workflow\"}-argo_workflow_status_start_time{workflow=\"$Workflow\"}"
    }
   ]
  },
  { "title": "Workflow status", "type": "text", "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 }, "content": "# $Phase" },
  {
   "title": "Nodes count",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(argo_workflow_node_info{workflow=\"$Workflow\"})"
    }
   ]
  },
  {
   "title": "Nodes succeeded",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(argo_workflow_node_status_succeeded{workflow=\"$Workflow\"} > 0)"
    }
   ]
  },
  {
   "title": "Nodes failed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(argo_workflow_node_status_failed{workflow=\"$Workflow\"} > 0)"
    }
   ]
  },
  {
   "title": "Nodes error",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(argo_workflow_node_status_error{workflow=\"$Workflow\"} > 0)"
    }
   ]
  },
  {
   "title": "Nodes skipped",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(argo_workflow_node_status_skipped{workflow=\"$Workflow\"} > 0)"
    }
   ]
  },
  {
   "title": "Nodes running",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(argo_workflow_node_status_running{workflow=\"$Workflow\"} > 0)"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (container_name )( rate(container_cpu_usage_seconds_total{image!=\"\",container_name!=\"POD\",pod_name=\"$Pod\"}[1m] ) )",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(container_name) (container_memory_usage_bytes{pod_name=\"$Pod\", container_name!=\"POD\"})",
     "legendFormat": "Current: {{ container_name }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (pod_name) (rate(container_network_receive_bytes_total{pod_name=\"$Pod\"}[1m])))",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  { "title": "Overall metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Workflows status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(argo_workflow_info)", "legendFormat": "total" },
    {
     "expr": "sum(argo_workflow_status_phase{phase=\"Running\"})",
     "legendFormat": "running"
    },
    {
     "expr": "sum(argo_workflow_status_phase{phase=\"Succeeded\"})",
     "legendFormat": "succeeded"
    },
    {
     "expr": "sum(argo_workflow_status_phase{phase=\"Failed\"})",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(argo_workflow_status_phase{phase=\"Error\"})",
     "legendFormat": "error"
    },
    {
     "expr": "sum(argo_workflow_status_phase{phase=\"Skipped\"})",
     "legendFormat": "skipped"
    }
   ]
  },
  {
   "title": "Nodes types",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(argo_workflow_node_info{type=\"Pod\"})",
     "legendFormat": "pod"
    },
    {
     "expr": "count(argo_workflow_node_info{type=\"Steps\"})",
     "legendFormat": "steps"
    },
    {
     "expr": "count(argo_workflow_node_info{type=\"StepGroup\"})",
     "legendFormat": "steps_group"
    },
    {
     "expr": "count(argo_workflow_node_info{type=\"DAG\"})",
     "legendFormat": "dag"
    },
    {
     "expr": "count(argo_workflow_node_info{type=\"TaskGroup\"})",
     "legendFormat": "task_group"
    },
    {
     "expr": "count(argo_workflow_node_info{type=\"Retry\"})",
     "legendFormat": "retry"
    },
    {
     "expr": "count(argo_workflow_node_info{type=\"Skipped\"})",
     "legendFormat": "skipped"
    },
    {
     "expr": "count(argo_workflow_node_info{type=\"Suspend\"})",
     "legendFormat": "suspend"
    }
   ]
  }
 ]
}