varReference:
- path: spec/mode
  kind: ClusterRbacConfig
- path: spec/selector
  kind: Gateway
- path: spec/servers/0/hosts/0
  kind: Gateway
- path: spec/http/route/destination/host
  kind: VirtualService
