apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- gateway.yaml

# configMapGenerator:
# - name: knative-serving-install-parameters
#   behavior: merge
#   env: params.env
# configurations:
# - params.yaml
