apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
resources:
- oidc.yaml
- istio-gateway.yaml
patchesStrategicMerge:
- envoy-filter.yaml
commonLabels:
  app.kubernetes.io/name: oidc-authservice
  app.kubernetes.io/instance: oidc-authservice-v1.0.0
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/component: oidc-authservice
  app.kubernetes.io/part-of: kubeflow
  app.kubernetes.io/version: v1.0.0
  app: oidc-authservice
