# The configuration for the ML pipelines APIServer
# Based on https://github.com/kubeflow/pipelines/blob/master/backend/src/apiserver/config/config.json
apiVersion: v1
data:
  # apiserver assumes the config is named config.json
  config.json: |
    {
      "DBConfig": {
        "DriverName": "mysql",
        "DataSourceName": "",
        "DBName": "$(mysqlDatabase)",
        "Host": "$(mysqlHost)",
        "Port": "3306",
        "User": "$(mysqlUser)",
        "Password": "$(mysqlPassword)",
        "GroupConcatMaxLen": "4194304"
      },
      "ObjectStoreConfig": {
        "AccessKey": "$(s3AccessKey)",
        "SecretAccessKey": "$(s3SecretKey)",
        "BucketName": "$(s3BucketName)",
        "Host": "$(s3EndpointHost)",
        "Port": "$(s3EndpointPort)",
        "Region": "$(s3Region)",
        "Secure": false
      },
      "InitConnectionTimeout": "6m",
      "DefaultPipelineRunnerServiceAccount": "pipeline-runner",
      "ML_PIPELINE_VISUALIZATIONSERVER_SERVICE_HOST": "ml-pipeline-ml-pipeline-visualizationserver",
      "ML_PIPELINE_VISUALIZATIONSERVER_SERVICE_PORT": 8888
    }
kind: ConfigMap
metadata:
  name: ml-pipeline-config
