apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- service-account.yaml
- cluster-role-binding.yaml
- config-map.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
