---
version: 1
kind: component
meta:
  name: prometheus
  brief: Prometheus monitoring service
  source:
    dir: ../../components/prometheus

requires:
  - kubernetes
  - helm
  - tiller

provides:
  - prometheus

parameters:
  - name: component.ingress.ssoFqdn
  - name: dns.domain
    env: DOMAIN_NAME
  - name: component.prometheus
    parameters:
    - name:  name
      value: prometheus
      env:   COMPONENT_NAME
    - name:  namespace
      brief: Kubernetes namespace to install into
      value: prometheus
      env:   NAMESPACE
    - name:  version
      brief: Prometheus version
      value: v2.3.2
    - name:  rbac.enabled
      value: true
    - name:  psp.enabled
      value: true
    - name:  ingress.enabled
      value: true
    - name:  ingress.urlPrefix
      value: prometheus
    - name:  ingress.path
      value: /
    - name: backend.timescale.name
      value: ""
    - name: backend.timescale.namespace
      value: ""
  - name: component.prometheus.alertmanager
    parameters:
    - name:  version
      brief: Alertmanager version
      value: v0.15.2
    - name:  ingress.enabled
      value: true
    - name:  ingress.urlPrefix
      value: alertmanager
    - name:  ingress.path
      value: /
  - name: component.prometheus.grafana
    parameters:
    - name:  version
      brief: Grafana version
      value: 5.2.3
    - name:  ingress.enabled
      value: true
    - name:  ingress.urlPrefix
      value: grafana

templates:
  files:
    - "*.template"

outputs:
  - name: component.prometheus.url
    brief: Prometheus URL
    value: http://${component.prometheus.ingress.urlPrefix}.${component.ingress.ssoFqdn}
  - name: component.prometheus.alertmanager_url
    brief: Alertmanager URL
    value: http://${component.prometheus.alertmanager.ingress.urlPrefix}.${component.ingress.ssoFqdn}
  - name: component.prometheus.grafana_url
    brief: Grafana URL
    value: http://${component.prometheus.grafana.ingress.urlPrefix}.${component.ingress.ssoFqdn}
