apiVersion: {{ template "prometheus-operator.apiVersion" . }}
kind: ServiceMonitor
metadata:
  labels:
    app: {{ template "exporter-autoscaler.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: cluster-autoscaler
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    prometheus: {{ .Release.Name }}
    {{- if .Values.additionalServiceMonitorLabels }}
{{ toYaml .Values.additionalServiceMonitorLabels | indent 4 }}
    {{- end }}
  name: {{ template "exporter-autoscaler.fullname" . }}
spec:
  jobLabel: component
  selector:
    matchLabels:
      app: {{ template "exporter-autoscaler.name" . }}
      component: cluster-autoscaler
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http
    interval: 10s

