{{- if .Values.backend.enabled -}}
kind: Service
apiVersion: v1
metadata:
  name: prometheus-postgres-adapter
  namespace: prometheus
spec:
  selector:
    app: prometheus-pg-adapter
  ports:
  - protocol: TCP
    port: 9201 
    targetPort: 9201
{{- end -}}
