apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- kf-istio-resources.yaml

configMapGenerator:
- name: istio-parameters
  behavior: merge
  env: params.env
configurations:
- params.yaml
commonLabels:
  app.kubernetes.io/name: kubeflow-gateway
  app.kubernetes.io/instance: istio
  app.kubernetes.io/managed-by: kfctl
  app.kubernetes.io/component: istio
  app.kubernetes.io/part-of: kubeflow
  kustomize.component: istio
  app: kubeflow
