---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default
allowVolumeExpansion: true
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
allowVolumeExpansion: true
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
allowVolumeExpansion: true
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
