apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: stackinfos.agilestacks.com
spec:
  group: agilestacks.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Cluster
  names:
    plural: stackinfos
    singular: stackinfo
    kind: StackInfo
    shortNames:
    - si
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
          - domainName
          properties:
            domainName:
              type: string
            envUrl:
              type: string
            instanceUrl:
              type: string
            stateFileUrl:
              type: string
