apiVersion: {{ template "prometheus-operator.apiVersion" . }}
kind: ServiceMonitor
metadata:
  labels:
    app: {{ template "exporter-traefik.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: traefik
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    prometheus: {{ .Release.Name }}
    {{- if .Values.additionalServiceMonitorLabels }}
{{ toYaml .Values.additionalServiceMonitorLabels | indent 4 }}
    {{- end }}
  name: {{ template "exporter-traefik.fullname" . }}
spec:
  jobLabel: component
  selector:
    matchLabels:
      app: {{ template "exporter-traefik.name" . }}
      component: traefik
  namespaceSelector:
    matchNames:
      - "ingress"
  endpoints:
  - port: metrics
    interval: 30s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
