apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: oidcs.auth.agilestacks.com
spec:
  group: auth.agilestacks.com
  names:
    kind: Oidc
    plural: oidcs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            id:
              description: Client ID and secret used to identify the client.
              type: string
            logoURL:
              type: string
            name:
              description: Name and LogoURL used when displaying this client to the
                end user.
              type: string
            public:
              description: Public clients must use either use a redirectURL 127.0.0.1:X
                or "urn:ietf:wg:oauth:2.0:oob"
              type: boolean
            redirectURIs:
              description: A registered set of redirect URIs. When redirecting from
                dex to the client, the URI requested to redirect to MUST match one
                of these values, unless the client is "public".
              items:
                type: string
              type: array
            secret:
              type: string
            trustedPeers:
              description: TrustedPeers are a list of peers which can issue tokens
                on this client's behalf using the dynamic "oauth2:server:client_id:(client_id)"
                scope. If a peer makes such a request, this client's ID will appear
                as the ID Token's audience.  Clients inherently trust themselves.
              items:
                type: string
              type: array
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
