apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: postgresql
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    prometheus: {{ .Release.Name }}
  name: {{ template "fullname" . }}
spec:
  jobLabel: {{ template "fullname" . }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      component: postgresql
  namespaceSelector:
    matchNames:
      - "automation-hub"
  endpoints:
  - port: http-metrics
    interval: 15s
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
