apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- config-map.yaml
configMapGenerator:
- name: pipeline-external-mysql-parameters
  env: params.env
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: mysqlHost
  objref:
    kind: ConfigMap
    name: pipeline-external-mysql-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.mysqlHost
- name: mysqlUser
  objref:
    kind: ConfigMap
    name: pipeline-external-mysql-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.mysqlUser
- name: mysqlDatabase
  objref:
    kind: ConfigMap
    name: pipeline-external-mysql-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.mysqlDatabase
- name: mysqlPassword
  objref:
    kind: ConfigMap
    name: pipeline-external-mysql-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.mysqlPassword
- name: mysqlHost
  objref:
    kind: ConfigMap
    name: pipeline-external-mysql-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.mysqlHost
- name: s3BucketName
  objref:
    kind: ConfigMap
    name: pipeline-external-mysql-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.s3BucketName
- name: s3AccessKey
  objref:
    kind: ConfigMap
    name: pipeline-external-mysql-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.s3AccessKey
- name: s3SecretKey
  objref:
    kind: ConfigMap
    name: pipeline-external-mysql-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.s3SecretKey
- name: s3EndpointHost
  objref:
    kind: ConfigMap
    name: pipeline-external-mysql-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.s3EndpointHost
- name: s3EndpointPort
  objref:
    kind: ConfigMap
    name: pipeline-external-mysql-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.s3EndpointPort
- name: s3Region
  objref:
    kind: ConfigMap
    name: pipeline-external-mysql-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.s3Region
configurations:
- params.yaml
