apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "exporter-argo.name" . }}
    component: argo
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ template "exporter-argo.fullname" . }}
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: telemetry
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    k8s-app: argo-metrics
  type: ClusterIP
