apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    component: node-exporter
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  type: {{ .Values.node_exporter.service.type }}
  ports:
  - name: metrics
    port: {{ .Values.node_exporter.service.externalPort }}
    protocol: TCP
  selector:
    app: {{ template "fullname" . }}
    component: node-exporter
    release: {{ .Release.Name }}
