FROM docker.io/agilestacks/jenkins:2.46.1-3

ENV  JENKINS_URL        ${component.jenkins.namespace}.app.${dns.domain}
ENV  GITHUB_DEPLOY_KEY  ${agilestacks.jenkins.github_key}

COPY init.groovy.d/*.groovy /usr/share/jenkins/ref/init.groovy.d/

# COPY secrets/github.txt /usr/share/jenkins/ref/agilestacks/github-key.txt