apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "name" . }}
    component: postgresql
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  name: {{ template "fullname" . }}
  namespace: automation-hub
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 9187
      protocol: TCP
      targetPort: 9187
  selector:
    app: automation-hub-db-postgresql
  type: ClusterIP
