---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  encrypted: "true"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: st1
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
provisioner: kubernetes.io/aws-ebs
parameters:
  type: st1
  encrypted: "true"
