apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}-config
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  postgres-url: postgres://{{ .Values.postresUser }}@{{ .Values.postgresUrl }}:{{ .Values.postgresPort }}/{{ .Values.postgresDatabase }}
  postgres-port:  {{ .Values.postgresPort | quote }}
