apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pgweb
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        provider:  agilestacks.com
        project:   postgresql
        qualifier: pgweb
    spec:
      containers:
      - name: pgweb
        image: "sosedoff/pgweb:0.9.7"
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: {{ template "fullname" . }}
              key: database-url
        ports:
        - name: http
          containerPort: 8081
        livenessProbe:
          httpGet:
            port: http
          initialDelaySeconds: 1
        readinessProbe:
          httpGet:
            port: http
          initialDelaySeconds: 1
