---
version: 1
kind: component
meta:
  name: argo
  brief: The workflow engine for Kubernetes
  source:
    dir: ../../components/argo

requires:
  - kubernetes
  - ingress
provides:
  - argo
  - argo-events

parameters:
- name: component.ingress.fqdn
- name: component.ingress.ssoUrlPrefix
- name: terraform.bucket.name
  env: STATE_BUCKET
- name: terraform.bucket.region
  env: STATE_REGION
- name: dns.domain
  env: DOMAIN_NAME
- name: cloud.region
  kind: user
  env: AWS_DEFAULT_REGION
- name: component.argo
  parameters:
  - name: name
    value: argo
    env: TF_VAR_component
  - name: replicas
    value: 1
  - name: namespace
    value: argoproj
    env: NAMESPACE
  - name: repo.bucket.name
    value: ${terraform.bucket.name}
    env: TF_VAR_bucket_name
  - name: repo.bucket.region
    value: ${terraform.bucket.region}
    env: TF_VAR_bucket_region
  - name: repo.bucket.insecure
    value: "false"
  - name: repo.bucket.keyPrefix
    value: ""
    empty: allow
  - name: serviceAccount
    value: argo
  - name: ingress.baseDomain
    value: ${component.ingress.ssoUrlPrefix}.${dns.domain}
  - name: chart.version
    value: '>0.0.0-0'
    env: CHART_VERSION
outputs:
- name: component.argo.repo.accessKey
  brief: Argo backend access key
  fromTfVar: access_key_id
- name: component.argo.repo.secretKey
  brief: Argo backend secret key
  fromTfVar: secret_access_key
- name: component.argo.repo
  brief: Argo backend S3 or Minio
  value: s3
- name: component.argo.repo.bucket.name
  brief: Argo backend bucket name
  value: ${component.argo.repo.bucket.name}
- name: component.argo.repo.bucket.region
  brief: Argo backend bucket region
  value: ${component.argo.repo.bucket.region}
- name: component.argo.repo.bucket.endpoint
  brief: Argo backend bucket service endpoint
  fromTfVar: endpoint
- name: component.argo.repo.bucket.insecure
  brief: Argo backend bucket insecure
  value: ${component.argo.repo.bucket.insecure}
- name: component.argo.repo.bucket.keyPrefix
  brief: Argo backend bucket key
  value: ${component.argo.repo.bucket.keyPrefix}
- name: component.argo.repo.iam.username
  brief: Name of the IAM user who have access to artifacts repository
  fromTfVar: iam_user_name
- name: component.argo.repo.iam.arn
  brief: ARN of the IAM user who have access to artifacts repository
  fromTfVar: iam_user_arn
- name: component.argo.ingress
  brief: URL to connect to argo-ui
  value: ${component.argo.name}.${component.argo.ingress.baseDomain}
- name: component.argo.namespace
  brief: Namespace where Argo has been installed
  value: ${component.argo.namespace}
- name:  component.argo.events.webhook.service.url
  value: http://webhook.${component.argo.namespace}.svc.cluster.local:8080
templates:
  files:
  - "*.template"
