---
version: 1
kind: component
meta:
  name: argo
  brief: The workflow engine for Kubernetes
  source:
    dir: ../../components/argo

requires:
  - kubernetes
  - ingress
provides:
  - argo

parameters:
- name: component.ingress.fqdn
- name: component.ingress.ssoUrlPrefix
- name: terraform.bucket.name
  env: STATE_BUCKET
- name: terraform.bucket.region
  env: STATE_REGION
- name: dns.domain
  env: DOMAIN_NAME
- name: cloud.region
  kind: user
  env: AWS_DEFAULT_REGION
- name: component.argo
  parameters:
  - name: name
    value: argo
    env: TF_VAR_component
  - name: replicas
    value: 4
  - name: namespace
    value: argoproj
    env: NAMESPACE
  - name: bucket
    value: ${terraform.bucket.name}
    env: TF_VAR_bucket_name
  - name: serviceAccount
    value: argo
  - name: ingress.baseDomain
    value: ${component.ingress.ssoUrlPrefix}.${dns.domain}
  - name: chart.version
    value: '>0.0.0-0'
    env: CHART_VERSION
outputs:
- name: component.argo.backend
  brief: Argo backend S3 or Minio
  value: s3://${terraform.bucket.name}/components/argo
- name: component.argo.ingress
  brief: URL to connect to argo-ui
  value: ${component.argo.name}.${component.argo.ingress.baseDomain}
- name: component.argo.namespace
  brief: Namespace where Argo has been installed
  value: ${component.argo.namespace}
templates:
  files:
  - "*.template"
  - "events/*.template"
