apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: aws-persistent
  annotations: 
    storageclass.kubernetes.io/is-default-class: true
parameters:
  encrypted: "false"
  type: gp2
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate
