apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spinnaker
  namespace: spinnaker
  labels:
    k8s-addon: ingress-nginx.addons.k8s.io
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - spinnaker.app.anton3.base.devops.delivery
    secretName: spinnaker-tls
  rules:
  - host: spinnaker.app.anton3.base.devops.delivery
    http:
      paths:
      - path: /
        backend:
          serviceName: spin-deck
          servicePort: 9000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spinnaker-api
  namespace: spinnaker
  labels:
    k8s-addon: ingress-nginx.addons.k8s.io
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - api.spinnaker.app.anton3.base.devops.delivery
    secretName: spinnaker-tls
  rules:
  - host: api.spinnaker.app.anton3.base.devops.delivery
    http:
      paths:
      - path: /
        backend:
          serviceName: spin-gate
          servicePort: 8084
