apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "etcd-backup-operator.fullname" . }}
  labels:
    name: {{ template "etcd-backup-operator.fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ template "etcd-backup-operator.fullname" . }}
    spec:
      containers:
      - name: etcd-backup-operator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        command:
        - etcd-backup-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
