apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  {{ template "etcd-restore-operator.fullname" . }}
  labels:
    name: {{ template "etcd-restore-operator.fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ template "etcd-restore-operator.fullname" . }}
    spec:
      containers:
      - name: etcd-restore-operator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        command:
        - etcd-restore-operator
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SERVICE_ADDR
          value: "{{ template "etcd-restore-operator.fullname" . }}:19999"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "etcd-restore-operator.fullname" . }}
spec:
  selector:
    name: {{ template "etcd-restore-operator.fullname" . }}
  ports:
  - protocol: TCP
    port: 19999
