{{- if default "" .Values.externalUrl }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "gitlab-ce.fullname" . }}
  labels:
    app: {{ template "gitlab-ce.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "gitlab-ce.fullname" . }}
    spec:
      initContainers:
      - name: init-gitlab-db
        image: postgres:9.6
        command: 
        - "sh"
        - "-c"
        - psql -c "create database {{ .Values.gitlab.database }};" && psql -c "create user {{ .Values.gitlab.databaseUser }} with unencrypted password '{{ .Values.gitlab.databasePassword }}';" &&  psql -c "grant all privileges on database {{ .Values.gitlab.database }} to {{ .Values.gitlab.databaseUser }};" || true
        env:
        - name: PGHOST
          value: {{ .Values.postgresql.postgresHostname }}
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: admin-db-user
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: admin-db-password
        - name: PGDATABASE
          value: {{ .Values.postgresql.postgresDatabase }}
      - name: add-gitlab-extension
        image: postgres:9.6
        command: 
        - "sh"
        - "-c"
        - psql -c 'CREATE EXTENSION IF NOT EXISTS "pg_trgm"'
        env:
        - name: PGHOST
          value: {{ .Values.postgresql.postgresHostname }}
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: admin-db-user
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: admin-db-password
        - name: PGDATABASE
          value: {{ .Values.gitlab.database }}
      containers:
      - name: {{ template "gitlab-ce.fullname" . }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        env:
        ## General GitLab Configs
        ##
        # This is a free-form env var that GitLab Omnibus uses to configure
        # everything. We're passing this in from a configmap and pulling some
        # of the values from the env vars defined below. This is done to
        # avoid leaving secrets visible in kubectl.
        - name: GITLAB_OMNIBUS_CONFIG
          valueFrom:
            configMapKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: gitlab_omnibus_config
        - name: GITLAB_ROOT_PASSWORD
        {{- if default "" .Values.gitlabRootPassword }}
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: gitlab-root-password
        {{ end }}
        - name: EXTERNAL_URL
          value: {{ default "" .Values.externalUrl | quote }}
        ## DB configuration
        ##
        - name: DB_HOSTNAME
          value: {{ .Values.postgresql.postgresHostname }}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: db-password
        - name: DB_DATABASE
          value: {{ .Values.gitlab.database | quote }}
        ## Redis configuration
        ##
        - name: REDIS_HOST
          value: {{ template "redis.fullname" . }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "gitlab-ce.fullname" . }}
              key: redis-password
        ports:
        - name: registry
          containerPort: 4567
        - name: ssh
          containerPort: 22
        - name: http
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /help
            port: http
          # This pod takes a very long time to start up. Be cautious when
          # lowering this value to avoid Pod death during startup.
          initialDelaySeconds: 300
          timeoutSeconds: 5
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 20
        readinessProbe:
          httpGet:
            path: /help
            port: http
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 20
        volumeMounts:
        - name: gitlab-etc
          mountPath: /etc/gitlab
        - name: gitlab-data
          mountPath: /gitlab-data
        resources:
{{ toYaml .Values.resources | indent 10 }}
      volumes:
      - name: gitlab-etc
      {{- if .Values.persistence.gitlabEtc.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "gitlab-ce.fullname" . }}-etc
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: gitlab-data
      {{- if .Values.persistence.gitlabData.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "gitlab-ce.fullname" . }}-data
      {{- else }}
        emptyDir: {}
      {{- end }}
{{ else }}
{{ end }}
