apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: authrequests.dex.coreos.com
spec:
  group: dex.coreos.com
  names:
    kind: AuthRequest
    listKind: AuthRequestList
    plural: authrequests
    singular: authrequest
  scope: Namespaced
  version: v1
