apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: oidcs.auth.agilestacks.com
spec:
  group: auth.agilestacks.com
  names:
    kind: Oidc
    plural: oidcs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            id:
              type: string
            logoURL:
              type: string
            name:
              type: string
            public:
              type: boolean
            redirectURIs:
              items:
                type: string
              type: array
            secret:
              type: string
            trustedPeers:
              items:
                type: string
              type: array
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
