apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list","watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: kube-system

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:latest
        env:
        - name: AWS_ACCESS_KEY_ID
          value: AKIA6FRW5AC4FS4ZIJHF
        - name: AWS_SECRET_ACCESS_KEY
          value: 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
        args:
        - --source=service
        - --source=ingress
        - --provider=aws
        - --registry=txt
        - --txt-owner-id=Z2WVM4LCRC2C1I
#        - --domain-filter=rick0g.dev.superhub.io # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
#        - --policy=upsert-only # would prevent ExternalDNS from deleting any records, omit to enable full synchronization
#        - --aws-zone-type=public # only look at public hosted zones (valid values are public, private or no value for both)
