apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jupyterhubnotebooks.agilestacks.com
spec:
  group: agilestacks.com
  names:
    kind: JupyterHubNotebook
    listKind: JupyterHubNotebookList
    plural: jupyterhubnotebooks
    singular: jupyterhubnotebook
  scope: Namespaced
  version: v1alpha1
