apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
patchesStrategicMerge:
- envoy-filter.yaml
configMapGenerator:
- name: add-anonymous-user-filter-parameters
  env: params.env

vars:
- name: namespace
  objref:
    kind: ConfigMap
    name: add-anonymous-user-filter-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.namespace
- name: istio_gateway
  objref:
    kind: ConfigMap
    name: add-anonymous-user-filter-parameters
    apiVersion: v1
  fieldref:
    fieldpath: data.istio_gateway
